# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: kinolan@unc.edu
author_name: Kira Nolan
custom_install: retrofit
include_docs: false
package_name: thor
project_description: ''
project_license: MIT
project_name: THOR
project_organization: knolan10
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
