repos:
    # Clear output from Jupyter notebooks before committing
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: Clear output from Jupyter notebooks
        description: Clear output from Jupyter notebooks.
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --clear-output
    # Prevent committing directly to main
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Prevent main branch commits
      - id: check-added-large-files
        args: ['--maxkb=500']
